### ISSUE TITLE
Error in workflow 'fspinilIo.aIfredv2.digitaIocean'

### ISSUE THREAD

**Issue by emilstahl** [fspinillo/alfred-digital-ocean#1]
After i set my token with dotoken i get the following error message.

![alfred-digital-ocean](https://cloud.githubusercontent.com/assets/3885790/6770923/ab9f7fe0-d0cf-11e4-97dd-27c8b9d158ee.png)

```
Error in workflow 'fspinilIo.aIfredv2.digitaIocean'
local variable ‘api_key‘ referen»ced'before assignment
```

**Comment by fspinillo** [comment]
Hi Emil, I just checked on my machine (fresh install of the workflow) and was able to call sshot from Alfed.

Can you open keychain access and search for 'digitalocean' to make sure it's set. If it's there, verify you selected read/write access when generating your token.

If that still doesn't work can you open Alfred preferences, select the Digital Ocean workflow and turn on debugging. Then run the workflow again and send me a gist of the error.

Thanks.

**Comment by emilstahl** [comment]
I reinistalled the worklflow. It works now, thanks!
